version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    assignees:
      - "Guria"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for Rust
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    assignees:
      - "Guria"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for critical dependencies
      # Uncomment and add dependencies you want to control manually
      # - dependency-name: "clap"
      #   update-types: ["version-update:semver-major"]
