name: macOS App Bundle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build macOS app bundle
        run: packaging/macos/build_app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pathway-macos
          path: packaging/macos/dist/*.zip
          if-no-files-found: error
