name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        run: |
          gh release create "${{ steps.get_version.outputs.version }}" \
            --title "Release ${{ steps.get_version.outputs.version }}" \
            --generate-notes \
            --latest \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: pathway
            asset_name: pathway-x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: pathway
            asset_name: pathway-x86_64-unknown-linux-musl

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: pathway
            asset_name: pathway-aarch64-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: pathway
            asset_name: pathway-x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: pathway
            asset_name: pathway-aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: pathway.exe
            asset_name: pathway-x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build release binary
        working-directory: ./core
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ] && [ "${{ matrix.target }}" != "aarch64-unknown-linux-gnu" ]; then
            strip core/target/${{ matrix.target }}/release/${{ matrix.binary_name }}
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            strip core/target/${{ matrix.target }}/release/${{ matrix.binary_name }}
          fi

      - name: Create archive
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a dist/${{ matrix.asset_name }}.zip ./core/target/${{ matrix.target }}/release/${{ matrix.binary_name }}
          else
            tar czf dist/${{ matrix.asset_name }}.tar.gz -C ./core/target/${{ matrix.target }}/release ${{ matrix.binary_name }}
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ (matrix.os == 'windows-latest' && format('./dist/{0}.zip', matrix.asset_name)) || format('./dist/{0}.tar.gz', matrix.asset_name) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-crate:
    name: Publish to crates.io
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        working-directory: ./core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --dry-run
          # Uncomment the next line when ready to publish
          # cargo publish
