name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: release-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
            if ! echo "$TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
              echo "Invalid tag format: $TAG (expected vMAJOR.MINOR.PATCH)"; exit 1
            fi
            echo "version=$TAG" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Verify tag exists (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: gh api repos/${{ github.repository }}/git/ref/tags/${{ steps.get_version.outputs.version }} >/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: pathway
            asset_name: pathway-x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: pathway
            asset_name: pathway-x86_64-unknown-linux-musl

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: pathway
            asset_name: pathway-aarch64-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: pathway
            asset_name: pathway-x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: pathway
            asset_name: pathway-aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: pathway.exe
            asset_name: pathway-x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-registry-${{ hashFiles('core/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-index-${{ hashFiles('core/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: core/target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-${{ hashFiles('core/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-build-

      - name: apt-get update (once)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get install -y musl-tools

      - name: Build release binary
        working-directory: ./core
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest' && matrix.target != 'aarch64-unknown-linux-gnu'
        run: |
          strip core/target/${{ matrix.target }}/release/${{ matrix.binary_name }}

      - name: Create archive
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a dist/${{ matrix.asset_name }}.zip ./core/target/${{ matrix.target }}/release/${{ matrix.binary_name }}
          else
            tar czf dist/${{ matrix.asset_name }}.tar.gz -C ./core/target/${{ matrix.target }}/release ${{ matrix.binary_name }}
          fi

      - name: Generate checksum
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            certutil -hashfile dist/${{ matrix.asset_name }}.zip SHA256 | awk 'NR==2{print $1"  dist/${{ matrix.asset_name }}.zip"}' > dist/${{ matrix.asset_name }}.zip.sha256
          else
            shasum -a 256 dist/${{ matrix.asset_name }}.tar.gz > dist/${{ matrix.asset_name }}.tar.gz.sha256
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ (matrix.os == 'windows-latest' && format('./dist/{0}.zip', matrix.asset_name)) || format('./dist/{0}.tar.gz', matrix.asset_name) }}
            ${{ (matrix.os == 'windows-latest' && format('./dist/{0}.zip.sha256', matrix.asset_name)) || format('./dist/{0}.tar.gz.sha256', matrix.asset_name) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-crate:
    if: vars.ENABLE_PUBLISH == 'true'
    name: Publish to crates.io
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        working-directory: ./core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --dry-run
          # Uncomment the next line when ready to publish
          # cargo publish
